### ISSUE TITLE
raises JSONDecodeError

### ISSUE THREAD

**Issue by tbrodbeck** [shoeffner/StudDP#4]
Hey! is this still working? 😬

Throws this error:
```
~/B/n/s/STT studDP -c                                                                          9:24
[INFO]: Logging initialized
[INFO]: Loading KWallet
[INFO]: Loading SecretService
[INFO]: Loading Windows
[INFO]: Loading chainer
[INFO]: Loading macOS
[INFO]: Loading Gnome
[INFO]: Loading Google
[INFO]: Loading Windows (alt)
[INFO]: Loading file
[INFO]: Loading keyczar
[INFO]: Loading multi
[INFO]: Loading pyfs
[INFO]: Listing Courses...
Traceback (most recent call last):
  File "/usr/local/bin/studDP", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/studdp/studdp.py", line 82, in main
    courses = client.get_courses()
  File "/usr/local/lib/python3.7/site-packages/studdp/model.py", line 226, in get_courses
    courses = json.loads(self._get('/api/courses').text)["courses"]
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by shoeffner** [comment]
I just checked the website, it could actually be that they don't have the rest plugin anymore – or they switched to an app-token-based authentication. At least I didn't find the settings for it anymore. Do you mind checking that? Also, what happens when you try the courses endpoint directly: https://studip.uos.de/plugins.php/restipplugin/api/courses ? For me it says I wouldn't have access anymore.

**Comment by tbrodbeck** [comment]
Oh okay, I have never used that tool before. I do not have access to the link anymore. Then probably it is an problem from studip. I might ask Tobias Thelen next time I see him.

**Comment by mschuwalow** [comment]
Sorry for being quiet here.
My understanding is that the plugin was deprecated a while ago and is no longer supported https://github.com/studip/studip-rest.ip.

Stud.ip should now expose another api https://docs.studip.de/develop/Entwickler/RESTAPI#toc4
